### ISSUE TITLE
Error when loading plugin

### ISSUE THREAD

**Issue by lachepootje** [GC-spigot/AdvancedRobots#18]
Every time i load / reload the plugin this comes up:

[ERROR] [AdvancedRobots] [AdvancedRobots] - Disabled due to no Vault dependency found!

[INFO] [AdvancedRobots] Disabling AdvancedRobots v1.2.5

[ERROR] Error occurred while enabling AdvancedRobots v1.2.5 (Is it up to date?)

org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register gc.advancedrobots.listeners.ArmorStandPlaceEvent@c1c96c85 while not enabled

at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:552) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at gc.advancedrobots.Core.onEnable(Core.java:52) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.reload(CraftServer.java:811) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.Bukkit.reload(Bukkit.java:576) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:696) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:430) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:394) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by GC-spigot** [comment]
You’re missing Vault plugin
