### ISSUE TITLE
Fisher dont fish

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedRobots#19]
The fisher dont do any fishing, even with fuel nothing happends

**Comment by Cryptics1999** [comment]
>.... [18:29:35 WARN]: [AdvancedRobots] Task #1738 for AdvancedRobots v1.2.5 generated an exception
java.lang.IllegalArgumentException: Item cannot be null
at org.apache.commons.lang.Validate.noNullElements(Validate.java:364) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.addItem(CraftInventory.java:289) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at gc.advancedrobots.handlers.TaskHandler.handleDrops(TaskHandler.java:213) ~[?:?]
at gc.advancedrobots.handlers.TaskHandler$1.run(TaskHandler.java:159) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1330) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1245) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:976) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
>.... [18:29:38 WARN]: [AdvancedRobots] Task #1738 for AdvancedRobots v1.2.5 generated an exception
java.lang.IllegalArgumentException: Item cannot be null
at org.apache.commons.lang.Validate.noNullElements(Validate.java:364) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.addItem(CraftInventory.java:289) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at gc.advancedrobots.handlers.TaskHandler.handleDrops(TaskHandler.java:213) ~[?:?]
at gc.advancedrobots.handlers.TaskHandler$1.run(TaskHandler.java:159) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1330) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1245) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:976) ~[sss1543624886003041694.bin:SSSpigot-1.15.2-20200626-6e695da]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
